### ISSUE TITLE
Reverse Proxy Server

### ISSUE THREAD

**Issue by veronicacannon** [HMUDesign/talk-nginx#6]
Simple explanation and examples please, of purpose, benefits and gotchas of reverse proxy servers.

Benefits:
- Speed
- Efficiency

Gotchas:
- IPs when reverse proxying
- Does not do caching
- Extra bit requires for Websockets

**Comment by christopherjbaker** [comment]
#2 #3 and #4 are all examples of this. #5 will likely include it again. In other words, nginx is 3 things:
1. Reverse Proxy
2. Load Balancer (which depends on being a reverse proxy)
3. Static Content server, and there's really only one way to do this

**Comment by HMUDesign** [comment]
For future reference:

Benefits:
* Speed
* Efficiency

Gotchas:
* IPs when reverse proxying
* Does not do caching
* Extra bit requires for Websockets
