### ISSUE TITLE
Recommended  SSL Settings

### ISSUE THREAD

**Issue by veronicacannon** [HMUDesign/talk-nginx#8]
https://www.digitalocean.com/community/tutorials/how-to-install-an-ssl-certificate-from-a-commercial-certificate-authority

```
ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
ssl_prefer_server_ciphers on;
ssl_ciphers AES256+EECDH:AES256+EDH:!aNULL;
```

Confirm that these settings are recommended.

**Comment by christopherjbaker** [comment]
Closing as duplicate of #5 HTTPS, which will include the recommended settings.

**Comment by veronicacannon** [comment]
Thanks!
